// 내 풀이,, gpt가 알려줬는데 틀림ㅎ; 
SELECT BOOK_IDPUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021  
AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;


// TODO: 복습!
// 정답 풀이
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d')
FROM BOOK
WHERE DATE_FORMAT(PUBLISHED_DATE, '%Y') = '2021'  
AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;
